name: flutter_so_server
description: Flutter SO包分发服务器
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_cors_headers: ^0.1.5
  args: ^2.4.2
  path: ^1.8.3
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0